apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: users
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: users
        chat/tier: api
    spec:
      initContainers:
        - name: db-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z user-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
        - name: token-service-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Token service deployment"; while ! nc -z token-service 9000; do sleep 1; printf "-"; done; echo -e "  >> Token Service has started";']
        - name: email-service-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Email service deployment"; while ! nc -z email-service 9000; do sleep 1; printf "-"; done; echo -e "  >> Email Service has started";']
        - name: kafka-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: user-service
        imagePullPolicy: Never
        image: slimo300/user-service
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_PASSWORD
        - name: MYSQL_ADDRESS
          value: user-mysql:3306
        - name: TOKEN_SERVICE_ADDRESS
          value: token-service:9000
        - name: EMAIL_SERVICE_ADDRESS
          value: email-service:9000
        - name: ORIGIN
          value: https://www.relrel.com
        - name: DOMAIN
          value: relrel.com
        - name: BROKER_ADDRESS
          value: kafka:9092
        envFrom:
        - secretRef:
            name: storage-credentials
        volumeMounts:
          - name: public-key
            mountPath: /rsa
      volumes:
        - name: public-key
          configMap:
            name: public-key
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    chat/app: users
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http