apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: microserviceschatapp
build:
  artifacts:
    - image: slimo300/email-service
      context: backend/email-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/group-service
      context: backend/group-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/message-service
      context: backend/message-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/search-service
      context: backend/search-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/token-service
      context: backend/token-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/user-service
      context: backend/user-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/ws-service
      context: backend/ws-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/webrtc-service
      context: backend/webrtc-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/webrtc-gateway-service
      context: backend/webrtc-gateway-service
      docker:
        dockerfile: Dockerfile
    - image: slimo300/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deploy/secrets/*
    - deploy/dbs/*
    - deploy/services/*
    - deploy/ingress-dev.yaml
    # - deploy/cert-manager/*
  helm:
    releases:
      # - name: cert-manager
      #   chartPath: jetstack/cert-manager
      #   version: 1.12.3
      - name: kafka
        chartPath: bitnami/kafka
        version: 20.0.6