apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-mysql
spec:
  # serviceName: messagemysql
  replicas: 1
  selector:
    matchLabels:
      chat/app: messages
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: messages
        chat/tier: database
    spec:
      containers:
      - name: message-mysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
        - secretRef:
            name: mysql-creds
        # volumeMounts:
        # - name: data
        #   mountPath: /var/lib/mysql
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #     annotations:
  #       volume.alpha.kubernetes.io/storage-class: standard
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: message-mysql
spec:
  clusterIP: None
  selector:
    chat/app: messages
    chat/tier: database
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql