apiVersion: apps/v1
kind: Deployment
metadata:
    name: emails-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            chat/app: emails
            chat/tier: api
    template:
        metadata:
            labels:
                chat/app: emails
                chat/tier: api
        spec:
            containers:
                - env:
                    - name: ORIGIN
                      value: http://www.relrel.org
                  envFrom:
                    - secretRef:
                        name: brevo-creds
                  image: slimo300/email-service:1.0.9
                  imagePullPolicy: Always
                  name: email-service
                  ports:
                    - containerPort: 9000
                      name: grpc
---
apiVersion: v1
kind: Service
metadata:
    name: email-service
spec:
    ports:
        - name: grpc
          port: 9000
          targetPort: 9000
    selector:
        chat/app: emails
        chat/tier: api
