apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: frontend
  template:
    metadata:
      labels:
        chat/app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: slimo300/frontend:1.0.1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: API_URL
          value: api.relrel.org
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: STORAGE_URL
        envFrom:
        - secretRef:
            name: turn-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    chat/app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http