apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: messages
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: messages
        chat/tier: api
    spec:
      initContainers:
        - name: db-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z message-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
        - name: rabbitmq-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of RabbitMQ broker"; while ! nc -z rabbitmq-service 5672; do sleep 1; printf "-"; done; echo -e "  >> RabbitMQ has started";']
        # - name: kafka-test
        #   image: busybox:1.31
        #   command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: message-service
        imagePullPolicy: Always
        image: slimo300/message-service:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: MYSQL_PASSWORD
        - name: MYSQL_ADDRESS
          value: message-mysql:3306
        - name: ORIGIN
          value: https://www.relrel.org
        envFrom:
        - configMapRef:
            name: broker-config
        - secretRef:
            name: storage-credentials
        volumeMounts:
          - name: public-key
            mountPath: /rsa
      volumes:
        - name: public-key
          configMap:
            name: public-key
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    chat/app: messages
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http