apiVersion: apps/v1
kind: Deployment
metadata:
    name: users-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            chat/app: users
            chat/tier: api
    template:
        metadata:
            labels:
                chat/app: users
                chat/tier: api
        spec:
            containers:
                - env:
                    - name: MYSQL_DATABASE
                      valueFrom:
                        secretKeyRef:
                            key: MYSQL_DATABASE
                            name: mysql-creds
                    - name: MYSQL_USER
                      valueFrom:
                        secretKeyRef:
                            key: MYSQL_USER
                            name: mysql-creds
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            key: MYSQL_PASSWORD
                            name: mysql-creds
                    - name: MYSQL_ADDRESS
                      value: user-mysql:3306
                    - name: TOKEN_SERVICE_ADDRESS
                      value: token-service:9000
                    - name: EMAIL_SERVICE_ADDRESS
                      value: email-service:9000
                    - name: ORIGIN
                      value: https://www.relrel.org
                    - name: DOMAIN
                      value: relrel.org
                  envFrom:
                    - configMapRef:
                        name: broker-config
                    - secretRef:
                        name: storage-credentials
                  image: slimo300/user-service:1.0.3
                  imagePullPolicy: Always
                  name: user-service
                  ports:
                    - containerPort: 8080
                      name: http
                  volumeMounts:
                    - mountPath: /rsa
                      name: public-key
            initContainers:
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z user-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";
                  image: busybox:1.31
                  name: db-test
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of Token service deployment"; while ! nc -z token-service 9000; do sleep 1; printf "-"; done; echo -e "  >> Token Service has started";
                  image: busybox:1.31
                  name: token-service-test
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of Email service deployment"; while ! nc -z email-service 9000; do sleep 1; printf "-"; done; echo -e "  >> Email Service has started";
                  image: busybox:1.31
                  name: email-service-test
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of RabbitMQ broker"; while ! nc -z rabbitmq-service 5672; do sleep 1; printf "-"; done; echo -e "  >> RabbitMQ has started";
                  image: busybox:1.31
                  name: rabbitmq-test
            volumes:
                - configMap:
                    name: public-key
                  name: public-key
---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    ports:
        - name: http
          port: 8080
          targetPort: 8080
    selector:
        chat/app: users
        chat/tier: api
