apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: webrtc-gateway
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: webrtc-gateway
        chat/tier: api
    spec:
      initContainers:
        - name: webrtc-gateway-redis-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Redis Server deployment"; while ! nc -z webrtc-gateway-redis 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server has started";']
        - name: rabbitmq-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of RabbitMQ broker"; while ! nc -z rabbitmq-service 5672; do sleep 1; printf "-"; done; echo -e "  >> RabbitMQ has started";']        
        # - name: kafka-test
        #   image: busybox:1.31
        #   command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: webrtc-gateway-service
        imagePullPolicy: Always
        image: slimo300/webrtc-gateway-service:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REDIS_ADDRESS
          value: webrtc-gateway-redis:6379
        - name: ORIGIN
          value: https://www.relrel.org
        envFrom:
        - configMapRef:
            name: broker-config
        - secretRef:
            name: redis-creds
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-gateway-service
spec:
  selector:
    chat/app: webrtc-gateway
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http