apiVersion: apps/v1
kind: Deployment
metadata:
    name: webrtc-gateway-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            chat/app: webrtc-gateway
            chat/tier: api
    template:
        metadata:
            labels:
                chat/app: webrtc-gateway
                chat/tier: api
        spec:
            containers:
                - env:
                    - name: REDIS_ADDRESS
                      value: webrtc-gateway-redis:6379
                    - name: ORIGIN
                      value: https://www.relrel.org
                  envFrom:
                    - configMapRef:
                        name: broker-config
                    - secretRef:
                        name: redis-creds
                  image: slimo300/webrtc-gateway-service:1.0.1
                  imagePullPolicy: Always
                  name: webrtc-gateway-service
                  ports:
                    - containerPort: 8080
                      name: http
            initContainers:
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of Redis Server deployment"; while ! nc -z webrtc-gateway-redis 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server has started";
                  image: busybox:1.31
                  name: webrtc-gateway-redis-test
                - command:
                    - sh
                    - -c
                    - echo -e "Checking for the availability of RabbitMQ broker"; while ! nc -z rabbitmq-service 5672; do sleep 1; printf "-"; done; echo -e "  >> RabbitMQ has started";
                  image: busybox:1.31
                  name: rabbitmq-test
---
apiVersion: v1
kind: Service
metadata:
    name: webrtc-gateway-service
spec:
    ports:
        - name: http
          port: 8080
          targetPort: 8080
    selector:
        chat/app: webrtc-gateway
        chat/tier: api
