// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	context "context"

	database "github.com/Slimo300/Microservices-Videocall-and-Chat-App/backend/group-service/database"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Slimo300/Microservices-Videocall-and-Chat-App/backend/group-service/models"

	uuid "github.com/google/uuid"
)

// GroupsMockRepository is an autogenerated mock type for the GroupsRepository type
type GroupsMockRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields:
func (_m *GroupsMockRepository) BeginTransaction() (database.GroupsRepository, error) {
	ret := _m.Called()

	var r0 database.GroupsRepository
	if rf, ok := ret.Get(0).(func() database.GroupsRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.GroupsRepository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTransaction provides a mock function with given fields:
func (_m *GroupsMockRepository) CommitTransaction() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateGroup provides a mock function with given fields: ctx, group
func (_m *GroupsMockRepository) CreateGroup(ctx context.Context, group *models.Group) (*models.Group, error) {
	ret := _m.Called(ctx, group)

	var r0 *models.Group
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) *models.Group); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Group) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateInvite provides a mock function with given fields: ctx, invite
func (_m *GroupsMockRepository) CreateInvite(ctx context.Context, invite *models.Invite) (*models.Invite, error) {
	ret := _m.Called(ctx, invite)

	var r0 *models.Invite
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invite) *models.Invite); ok {
		r0 = rf(ctx, invite)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Invite) error); ok {
		r1 = rf(ctx, invite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMember provides a mock function with given fields: ctx, member
func (_m *GroupsMockRepository) CreateMember(ctx context.Context, member *models.Member) (*models.Member, error) {
	ret := _m.Called(ctx, member)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(context.Context, *models.Member) *models.Member); ok {
		r0 = rf(ctx, member)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Member) error); ok {
		r1 = rf(ctx, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *GroupsMockRepository) CreateUser(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroup provides a mock function with given fields: ctx, groupID
func (_m *GroupsMockRepository) DeleteGroup(ctx context.Context, groupID uuid.UUID) (*models.Group, error) {
	ret := _m.Called(ctx, groupID)

	var r0 *models.Group
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Group); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteInvite provides a mock function with given fields: ctx, inviteID
func (_m *GroupsMockRepository) DeleteInvite(ctx context.Context, inviteID uuid.UUID) (*models.Invite, error) {
	ret := _m.Called(ctx, inviteID)

	var r0 *models.Invite
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Invite); ok {
		r0 = rf(ctx, inviteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, inviteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMember provides a mock function with given fields: ctx, memberID
func (_m *GroupsMockRepository) DeleteMember(ctx context.Context, memberID uuid.UUID) (*models.Member, error) {
	ret := _m.Called(ctx, memberID)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Member); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *GroupsMockRepository) DeleteUser(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupByID provides a mock function with given fields: ctx, groupID
func (_m *GroupsMockRepository) GetGroupByID(ctx context.Context, groupID uuid.UUID) (*models.Group, error) {
	ret := _m.Called(ctx, groupID)

	var r0 *models.Group
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Group); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInviteByID provides a mock function with given fields: ctx, inviteID
func (_m *GroupsMockRepository) GetInviteByID(ctx context.Context, inviteID uuid.UUID) (*models.Invite, error) {
	ret := _m.Called(ctx, inviteID)

	var r0 *models.Invite
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Invite); ok {
		r0 = rf(ctx, inviteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, inviteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberByID provides a mock function with given fields: ctx, memberID
func (_m *GroupsMockRepository) GetMemberByID(ctx context.Context, memberID uuid.UUID) (*models.Member, error) {
	ret := _m.Called(ctx, memberID)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Member); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberByUserGroupID provides a mock function with given fields: ctx, userID, groupID
func (_m *GroupsMockRepository) GetMemberByUserGroupID(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (*models.Member, error) {
	ret := _m.Called(ctx, userID, groupID)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Member); ok {
		r0 = rf(ctx, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *GroupsMockRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGroups provides a mock function with given fields: ctx, userID
func (_m *GroupsMockRepository) GetUserGroups(ctx context.Context, userID uuid.UUID) ([]*models.Group, error) {
	ret := _m.Called(ctx, userID)

	var r0 []*models.Group
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Group); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInvites provides a mock function with given fields: ctx, userID, num, offset
func (_m *GroupsMockRepository) GetUserInvites(ctx context.Context, userID uuid.UUID, num int, offset int) ([]*models.Invite, error) {
	ret := _m.Called(ctx, userID, num, offset)

	var r0 []*models.Invite
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*models.Invite); ok {
		r0 = rf(ctx, userID, num, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Invite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, num, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUserInvited provides a mock function with given fields: ctx, userID, groupID
func (_m *GroupsMockRepository) IsUserInvited(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, groupID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, groupID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackTransaction provides a mock function with given fields:
func (_m *GroupsMockRepository) RollbackTransaction() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroup provides a mock function with given fields: ctx, group
func (_m *GroupsMockRepository) UpdateGroup(ctx context.Context, group *models.Group) (*models.Group, error) {
	ret := _m.Called(ctx, group)

	var r0 *models.Group
	if rf, ok := ret.Get(0).(func(context.Context, *models.Group) *models.Group); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Group) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInvite provides a mock function with given fields: ctx, invite
func (_m *GroupsMockRepository) UpdateInvite(ctx context.Context, invite *models.Invite) (*models.Invite, error) {
	ret := _m.Called(ctx, invite)

	var r0 *models.Invite
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invite) *models.Invite); ok {
		r0 = rf(ctx, invite)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invite)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Invite) error); ok {
		r1 = rf(ctx, invite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMember provides a mock function with given fields: ctx, member
func (_m *GroupsMockRepository) UpdateMember(ctx context.Context, member *models.Member) (*models.Member, error) {
	ret := _m.Called(ctx, member)

	var r0 *models.Member
	if rf, ok := ret.Get(0).(func(context.Context, *models.Member) *models.Member); ok {
		r0 = rf(ctx, member)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Member) error); ok {
		r1 = rf(ctx, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *GroupsMockRepository) UpdateUser(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGroupsMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupsMockRepository creates a new instance of GroupsMockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupsMockRepository(t mockConstructorTestingTNewGroupsMockRepository) *GroupsMockRepository {
	mock := &GroupsMockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
