// Code generated by mockery v2.20.0. DO NOT EDIT.

package client

import (
	context "context"

	pb "github.com/Slimo300/chat-tokenservice/pkg/client/pb"
	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"

	uuid "github.com/google/uuid"
)

// MockTokenClient is an autogenerated mock type for the TokenClient type
type MockTokenClient struct {
	mock.Mock
}

// DeleteUserToken provides a mock function with given fields: ctx, refresh
func (_m *MockTokenClient) DeleteUserToken(ctx context.Context, refresh string) error {
	ret := _m.Called(ctx, refresh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refresh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPublicKey provides a mock function with given fields:
func (_m *MockTokenClient) GetPublicKey() *rsa.PublicKey {
	ret := _m.Called()

	var r0 *rsa.PublicKey
	if rf, ok := ret.Get(0).(func() *rsa.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	return r0
}

// NewPairFromRefresh provides a mock function with given fields: ctx, refresh
func (_m *MockTokenClient) NewPairFromRefresh(ctx context.Context, refresh string) (*pb.TokenPair, error) {
	ret := _m.Called(ctx, refresh)

	var r0 *pb.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pb.TokenPair, error)); ok {
		return rf(ctx, refresh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pb.TokenPair); ok {
		r0 = rf(ctx, refresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refresh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPairFromUserID provides a mock function with given fields: ctx, userID
func (_m *MockTokenClient) NewPairFromUserID(ctx context.Context, userID uuid.UUID) (*pb.TokenPair, error) {
	ret := _m.Called(ctx, userID)

	var r0 *pb.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*pb.TokenPair, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *pb.TokenPair); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockTokenClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTokenClient creates a new instance of MockTokenClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTokenClient(t mockConstructorTestingTNewMockTokenClient) *MockTokenClient {
	mock := &MockTokenClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
