apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-gateway-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: webrtc-gateway
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: webrtc-gateway
        chat/tier: database
    spec:
      containers:
      - name: redis
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
          name: redis
        envFrom:
        - secretRef:
            name: redis-creds
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-gateway-redis
spec:
  clusterIP: None
  selector:
    chat/app: webrtc-gateway
    chat/tier: database
  ports:
  - port: 6379
    targetPort: 6379
    name: redis