apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
spec:
  serviceName: elastic
  replicas: 1
  selector:
    matchLabels:
      chat/app: search
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: search
        chat/tier: database
    spec:
      containers:
      - name: elastic
        image: bitnami/elasticsearch:8
        ports:
        - containerPort: 9200
          name: elastic
        volumeMounts:
        - name: data
          mountPath: /bitnami/elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  clusterIP: None
  selector:
    chat/app: search
    chat/tier: database
  ports:
  - port: 9200
    targetPort: 9200
    name: elastic