apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      chat/app: tokens
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: tokens
        chat/tier: database
    spec:
      containers:
      - name: redis
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis/data
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: redispass
                key: REDIS_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  selector:
    chat/app: tokens
    chat/tier: database
  ports:
  - port: 6379
    targetPort: 6379
    name: redis