apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermysql
spec:
  # serviceName: usermysql
  replicas: 1
  selector:
    matchLabels:
      chat/app: users
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: users
        chat/tier: database
    spec:
      containers:
      - name: usermysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_DATABASE
          value: chatapp
        - name: MYSQL_USER
          value: chat
        - name: MYSQL_PASSWORD
          value: password12
        - name: MYSQL_ROOT_PASSWORD
          value: password123
        # volumeMounts:
        # - name: data
        #   mountPath: /var/lib/mysql
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #     annotations:
  #       volume.alpha.kubernetes.io/storage-class: standard
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: usermysql
spec:
  clusterIP: None
  selector:
    chat/app: users
    chat/tier: database
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql