apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wsmysql
spec:
  serviceName: wsmysql
  replicas: 1
  selector:
    matchLabels:
      chat/app: ws
      chat/tier: database
  template:
    metadata:
      labels:
        chat/app: ws
        chat/tier: database
    spec:
      containers:
      - name: wsmysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
        envFrom:
        - configMapRef:
            name: mysqlcreds
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wsmysql
spec:
  clusterIP: None
  selector:
    chat/app: ws
    chat/tier: database
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql