apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: default
spec:
  secretName: relrel-tls
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - www.relrel.com
    - api.relrel.com