apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: default
spec:
  secretName: chatapp-tls
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - www.chatapp.example
    - api.chatapp.example