apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Slimo300/Microservices-Videocall-and-Chat-App
    targetRevision: HEAD
    path: infra/k8s/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true