// Code generated by mockery v2.20.0. DO NOT EDIT.

package email

import (
	mock "github.com/stretchr/testify/mock"
)

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: tmpl, data
func (_m *MockEmailService) SendEmail(tmpl string, data EmailData) error {
	ret := _m.Called(tmpl, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, EmailData) error); ok {
		r0 = rf(tmpl, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockEmailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEmailService(t mockConstructorTestingTNewMockEmailService) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
