apiVersion: v1
kind: Secret
metadata:
  name: awssecrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <BASE64_AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <BASE64_AWS_SECRET_ACCESS_KEY>
  S3_BUCKET: <S3_BUCKET_NAME>