// Code generated by mockery v2.20.0. DO NOT EDIT.

package email

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailClient is an autogenerated mock type for the EmailServiceClient type
type MockEmailClient struct {
	mock.Mock
}

// SendResetPasswordEmail provides a mock function with given fields: ctx, in, opts
func (_m *MockEmailClient) SendResetPasswordEmail(ctx context.Context, in *EmailData, opts ...grpc.CallOption) (*Msg, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *Msg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *EmailData, ...grpc.CallOption) (*Msg, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *EmailData, ...grpc.CallOption) *Msg); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Msg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *EmailData, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendVerificationEmail provides a mock function with given fields: ctx, in, opts
func (_m *MockEmailClient) SendVerificationEmail(ctx context.Context, in *EmailData, opts ...grpc.CallOption) (*Msg, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *Msg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *EmailData, ...grpc.CallOption) (*Msg, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *EmailData, ...grpc.CallOption) *Msg); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Msg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *EmailData, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockEmailClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEmailClient creates a new instance of MockEmailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEmailClient(t mockConstructorTestingTNewMockEmailClient) *MockEmailClient {
	mock := &MockEmailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
