apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupsdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: groups
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: groups
        chat/tier: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Never
        image: chat/groupservice
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: https
        envFrom:
        - secretRef:
            name: awskey
---
apiVersion: v1
kind: Service
metadata:
  name: groupservice
spec:
  selector:
    chat/app: groups
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8090
    targetPort: 8090
    name: https