apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: search
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: search
        chat/tier: api
    spec:
      initContainers:
        - name: init-cont
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of ElasticSearch Server deployment"; while ! nc -z elastic 9200; do sleep 1; printf "-"; done; echo -e "  >> Elastic Search Server has started";']
        - name: kafka-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: search-service
        imagePullPolicy: Never
        image: chat/searchservice
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ES_ADDRESS
          value: http://elastic:9200
        - name: ES_USER
          value: ""
        - name: ES_PASS
          value: ""
        - name: ORIGIN
          value: https://www.relrel.com
        - name: BROKER_ADDRESS
          value: kafka:9092
        volumeMounts:
          - name: public-key
            mountPath: /rsa
      volumes:
        - name: public-key
          configMap:
            name: public-key
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    chat/app: search
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http