apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: search
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: search
        chat/tier: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Never
        image: chat/searchservice
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: https
        env:
        - name: TOKEN_SERVICE_ADDRESS
          value: tokenservice:9000
        - name: ORIGIN
          value: http://www.chatapp.example
        - name: BROKER_ADDRESS
          value: kafka:9092
        envFrom:
        - configMapRef:
            name: escreds
---
apiVersion: v1
kind: Service
metadata:
  name: searchservice
spec:
  selector:
    chat/app: search
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8090
    targetPort: 8090
    name: https