apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokensdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: tokens
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: tokens
        chat/tier: api
    spec:
      initContainers:
        - name: init-cont
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Redis Server deployment"; while ! nc -z tokenredis 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server has started";']
      containers:
      - name: tokenservice
        imagePullPolicy: Never
        image: chat/tokenservice
        ports:
        - containerPort: 9000
          name: grpc
        env:
        - name: REDIS_ADDRESS
          value: tokenredis:6379
        - name: REFRESH_DURATION
          value: 86400s
        - name: ACCESS_DURATION
          value: 1200s
        envFrom:
        - secretRef:
            name: refreshsecret
        - configMapRef:
            name: redispass
---
apiVersion: v1
kind: Service
metadata:
  name: tokenservice
spec:
  selector:
    chat/app: tokens
    chat/tier: api
  ports:
  - port: 9000
    targetPort: 9000
    name: grpc