apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokensdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: tokens
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: tokens
        chat/tier: api
    spec:
      containers:
      - name: tokenservice
        imagePullPolicy: Never
        image: chat/tokenservice
        ports:
        - containerPort: 9000
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: tokenservice
spec:
  selector:
    chat/app: tokens
    chat/tier: api
  ports:
  - port: 9000
    targetPort: 9000
    name: grpc