apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: users
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: users
        chat/tier: api
    spec:
      initContainers:
        - name: db-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z usermysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
        - name: tokenservice-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Token service deployment"; while ! nc -z tokenservice 9000; do sleep 1; printf "-"; done; echo -e "  >> Token Service has started";']
        - name: emailservice-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Email service deployment"; while ! nc -z emailservice 9000; do sleep 1; printf "-"; done; echo -e "  >> Email Service has started";']
        - name: kafka-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: user-service
        imagePullPolicy: Never
        image: chat/userservice
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: https
        env:
        - name: MYSQL_ADDRESS
          value: chat:password12@tcp(messagemysql:3306)/chatapp
        - name: TOKEN_SERVICE_ADDRESS
          value: tokenservice:9000
        - name: EMAIL_SERVICE_ADDRESS
          value: emailservice:9000
        - name: ORIGIN
          value: http://www.chatapp.example
        - name: DOMAIN
          value: chatapp.example
        - name: BROKER_ADDRESS
          value: kafka:9092
        envFrom:
        - secretRef:
            name: awssecrets
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    chat/app: users
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8090
    targetPort: 8090
    name: https