apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtcdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chat/app: webrtc
      chat/tier: api
  template:
    metadata:
      labels:
        chat/app: webrtc
        chat/tier: api
    spec:
      initContainers:
        - name: webrtcredis-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Redis Server deployment"; while ! nc -z webrtcredis 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server has started";']
        - name: tokenservice-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Token service deployment"; while ! nc -z tokenservice 9000; do sleep 1; printf "-"; done; echo -e "  >> Token Service has started";']
        - name: kafka-test
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of Kafka broker"; while ! nc -z kafka 9092; do sleep 1; printf "-"; done; echo -e "  >> Kafka has started";']
      containers:
      - name: webrtc-service
        imagePullPolicy: Never
        image: chat/webrtcservice
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_ADDRESS
          value: webrtcredis:6379
        - name: DB_PASSWORD
          value: redis
        - name: TOKEN_SERVICE_ADDRESS
          value: tokenservice:9000
        - name: ORIGIN
          value: https://www.relrel.com
        - name: BROKER_ADDRESS
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: webrtcservice
spec:
  selector:
    chat/app: webrtc
    chat/tier: api
  ports:
  - port: 8080
    targetPort: 8080
    name: http