name: email-service-test

on: 
  pull_request:
    paths:
      - 'backend/email-service/**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend/email-service
          args: --timeout=30m
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Test Go Code
        run: cd backend/email-service && go test ./...