name: webrtc-gateway-service-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/webrtc-gateway-service/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: cd backend/webrtc-gateway-service && docker build -t slimo300/webrtc-gateway-service .
      - name: Log In to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish an Image
        run: docker push slimo300/webrtc-gateway-service
      - name: Installing Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Saving our cluster config
        run: doctl kubernetes cluster kubeconfig save relrel
      - name: Update Deployment
        run: kubectl rollout restart webrtc-gateway-deployment