name: webrtc-service-deploy

on:
  push:
    branches: 
      - main
    paths:
      - backend/webrtc-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: cd backend/webrtc-service && docker build -t slimo300/webrtc-service .
      - name: Log In to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish an Image
        run: docker push slimo300/webrtc-service